<?php

// Data functions (insert, update, delete, form) for table Posts

// This script and data application were generated by AppGini 22.11
// Download AppGini for free from https://bigprof.com/appgini/download/

function Posts_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('Posts');
	if(!$arrPerm['insert']) return false;

	$data = [
		'caregoria_id' => Request::lookup('caregoria_id', ''),
		'tag_id' => Request::lookup('tag_id', ''),
		'title' => Request::val('title', ''),
		'conteudo' => Request::val('conteudo', ''),
		'data' => mysql_datetime(Request::val('data', '')),
		'midia' => Request::fileUpload('midia', [
			'maxSize' => 1048576,
			'types' => 'jpg|jpeg|gif|png',
			'noRename' => false,
			'dir' => '',
			'success' => function($name, $selected_id) {
				createThumbnail($name, getThumbnailSpecs('Posts', 'midia', 'dv'));
			},
			'failure' => function($selected_id, $fileRemoved) {
				if(!strlen(Request::val('SelectedID'))) return '';

				/* for empty upload fields, when saving a copy of an existing record, copy the original upload field */
				return existing_value('Posts', 'midia', Request::val('SelectedID'));
			},
		]),
	];

	if($data['caregoria_id'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Caregoria id': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['title'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Title': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}

	// hook: Posts_before_insert
	if(function_exists('Posts_before_insert')) {
		$args = [];
		if(!Posts_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('Posts', backtick_keys_once($data), $error);
	if($error)
		die("{$error}<br><a href=\"#\" onclick=\"history.go(-1);\">{$Translation['< back']}</a>");

	$recID = db_insert_id(db_link());

	update_calc_fields('Posts', $recID, calculated_fields()['Posts']);

	// hook: Posts_after_insert
	if(function_exists('Posts_after_insert')) {
		$res = sql("SELECT * FROM `Posts` WHERE `id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=[];
		if(!Posts_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('Posts', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) Posts_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function Posts_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function Posts_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('Posts', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Posts_before_delete
	if(function_exists('Posts_before_delete')) {
		$args = [];
		if(!Posts_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	// delete file stored in the 'midia' field
	$res = sql("SELECT `midia` FROM `Posts` WHERE `id`='{$selected_id}'", $eo);
	if($row = @db_fetch_row($res)) {
		if($row[0] != '') {
			@unlink(getUploadDir('') . $row[0]);
			$thumbDV = preg_replace('/\.(gif|png|jpg|jpeg|jpe)$/i', '_dv.$1', $row[0]);
			$thumbTV = preg_replace('/\.(gif|png|jpg|jpeg|jpe)$/i', '_tv.$1', $row[0]);
			@unlink(getUploadDir('') . $thumbTV);
			@unlink(getUploadDir('') . $thumbDV);
		}
	}

	sql("DELETE FROM `Posts` WHERE `id`='{$selected_id}'", $eo);

	// hook: Posts_after_delete
	if(function_exists('Posts_after_delete')) {
		$args = [];
		Posts_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='Posts' AND `pkValue`='{$selected_id}'", $eo);
}

function Posts_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('Posts', $selected_id, 'edit')) return false;

	$data = [
		'caregoria_id' => Request::lookup('caregoria_id', ''),
		'tag_id' => Request::lookup('tag_id', ''),
		'title' => Request::val('title', ''),
		'conteudo' => Request::val('conteudo', ''),
		'data' => mysql_datetime(Request::val('data', '')),
		'midia' => Request::fileUpload('midia', [
			'maxSize' => 1048576,
			'types' => 'jpg|jpeg|gif|png',
			'noRename' => false,
			'dir' => '',
			'id' => $selected_id,
			'success' => function($name, $selected_id) {
				createThumbnail($name, getThumbnailSpecs('Posts', 'midia', 'dv'));
			},
			'removeOnSuccess' => true,
			'removeOnRequest' => true,
			'remove' => function($selected_id) {
				// delete old file from server
				$oldFile = existing_value('Posts', 'midia', $selected_id);
				if(!$oldFile) return;

				@unlink(getUploadDir('') . $oldFile);

				// delete thumbnails
				preg_match('/^[a-z0-9_]+\.(gif|png|jpg|jpeg|jpe)$/i', $oldFile, $m);
				$thumbDV = str_replace(".{$m[1]}ffffgggg", "_dv.{$m[1]}", $oldFile . 'ffffgggg');
				$thumbTV = str_replace(".{$m[1]}ffffgggg", "_tv.{$m[1]}", $oldFile . 'ffffgggg');
				@unlink(getUploadDir('') . $thumbTV);
				@unlink(getUploadDir('') . $thumbDV);
			},
			'failure' => function($selected_id, $fileRemoved) {
				if($fileRemoved) return '';
				return existing_value('Posts', 'midia', $selected_id);
			},
		]),
	];

	if($data['caregoria_id'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Caregoria id': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['title'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Title': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('Posts', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: Posts_before_update
	if(function_exists('Posts_before_update')) {
		$args = ['old_data' => $old_data];
		if(!Posts_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'Posts', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="Posts_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('Posts', $data['selectedID'], calculated_fields()['Posts']);

	// hook: Posts_after_update
	if(function_exists('Posts_after_update')) {
		$res = sql("SELECT * FROM `Posts` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!Posts_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='Posts' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function Posts_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	// mm: get table permissions
	$arrPerm = getTablePermissions('Posts');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}

	$filterer_caregoria_id = Request::val('filterer_caregoria_id');
	$filterer_tag_id = Request::val('filterer_tag_id');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: caregoria_id
	$combo_caregoria_id = new DataCombo;
	// combobox: tag_id
	$combo_tag_id = new DataCombo;

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm['view']) return $Translation['tableAccessDenied'];

		// mm: who is the owner?
		$ownerGroupID = sqlValue("SELECT `groupID` FROM `membership_userrecords` WHERE `tableName`='Posts' AND `pkValue`='" . makeSafe($selected_id) . "'");
		$ownerMemberID = sqlValue("SELECT LCASE(`memberID`) FROM `membership_userrecords` WHERE `tableName`='Posts' AND `pkValue`='" . makeSafe($selected_id) . "'");

		if($arrPerm['view'] == 1 && getLoggedMemberID() != $ownerMemberID) return $Translation['tableAccessDenied'];
		if($arrPerm['view'] == 2 && getLoggedGroupID() != $ownerGroupID) return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = 0;
		if(($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3) {
			$AllowUpdate = 1;
		}

		$res = sql("SELECT * FROM `Posts` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'Posts_view.php', false);
		}
		$combo_caregoria_id->SelectedData = $row['caregoria_id'];
		$combo_tag_id->SelectedData = $row['tag_id'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_caregoria_id->SelectedData = $filterer_caregoria_id;
		$combo_tag_id->SelectedData = $filterer_tag_id;
	}
	$combo_caregoria_id->HTML = '<span id="caregoria_id-container' . $rnd1 . '"></span><input type="hidden" name="caregoria_id" id="caregoria_id' . $rnd1 . '" value="' . html_attr($combo_caregoria_id->SelectedData) . '">';
	$combo_caregoria_id->MatchText = '<span id="caregoria_id-container-readonly' . $rnd1 . '"></span><input type="hidden" name="caregoria_id" id="caregoria_id' . $rnd1 . '" value="' . html_attr($combo_caregoria_id->SelectedData) . '">';
	$combo_tag_id->HTML = '<span id="tag_id-container' . $rnd1 . '"></span><input type="hidden" name="tag_id" id="tag_id' . $rnd1 . '" value="' . html_attr($combo_tag_id->SelectedData) . '">';
	$combo_tag_id->MatchText = '<span id="tag_id-container-readonly' . $rnd1 . '"></span><input type="hidden" name="tag_id" id="tag_id' . $rnd1 . '" value="' . html_attr($combo_tag_id->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_caregoria_id__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['caregoria_id'] : htmlspecialchars($filterer_caregoria_id, ENT_QUOTES)); ?>"};
		AppGini.current_tag_id__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['tag_id'] : htmlspecialchars($filterer_tag_id, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(caregoria_id_reload__RAND__) == 'function') caregoria_id_reload__RAND__();
				if(typeof(tag_id_reload__RAND__) == 'function') tag_id_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function caregoria_id_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#caregoria_id-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_caregoria_id__RAND__.value, t: 'Posts', f: 'caregoria_id' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="caregoria_id"]').val(resp.results[0].id);
							$j('[id=caregoria_id-container-readonly__RAND__]').html('<span id="caregoria_id-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Categoria_view_parent]').hide(); } else { $j('.btn[id=Categoria_view_parent]').show(); }


							if(typeof(caregoria_id_update_autofills__RAND__) == 'function') caregoria_id_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Posts', f: 'caregoria_id' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_caregoria_id__RAND__.value = e.added.id;
				AppGini.current_caregoria_id__RAND__.text = e.added.text;
				$j('[name="caregoria_id"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Categoria_view_parent]').hide(); } else { $j('.btn[id=Categoria_view_parent]').show(); }


				if(typeof(caregoria_id_update_autofills__RAND__) == 'function') caregoria_id_update_autofills__RAND__();
			});

			if(!$j("#caregoria_id-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_caregoria_id__RAND__.value, t: 'Posts', f: 'caregoria_id' },
					success: function(resp) {
						$j('[name="caregoria_id"]').val(resp.results[0].id);
						$j('[id=caregoria_id-container-readonly__RAND__]').html('<span id="caregoria_id-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Categoria_view_parent]').hide(); } else { $j('.btn[id=Categoria_view_parent]').show(); }

						if(typeof(caregoria_id_update_autofills__RAND__) == 'function') caregoria_id_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_caregoria_id__RAND__.value, t: 'Posts', f: 'caregoria_id' },
				success: function(resp) {
					$j('[id=caregoria_id-container__RAND__], [id=caregoria_id-container-readonly__RAND__]').html('<span id="caregoria_id-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Categoria_view_parent]').hide(); } else { $j('.btn[id=Categoria_view_parent]').show(); }

					if(typeof(caregoria_id_update_autofills__RAND__) == 'function') caregoria_id_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function tag_id_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#tag_id-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_tag_id__RAND__.value, t: 'Posts', f: 'tag_id' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="tag_id"]').val(resp.results[0].id);
							$j('[id=tag_id-container-readonly__RAND__]').html('<span id="tag_id-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Tags_view_parent]').hide(); } else { $j('.btn[id=Tags_view_parent]').show(); }


							if(typeof(tag_id_update_autofills__RAND__) == 'function') tag_id_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Posts', f: 'tag_id' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_tag_id__RAND__.value = e.added.id;
				AppGini.current_tag_id__RAND__.text = e.added.text;
				$j('[name="tag_id"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Tags_view_parent]').hide(); } else { $j('.btn[id=Tags_view_parent]').show(); }


				if(typeof(tag_id_update_autofills__RAND__) == 'function') tag_id_update_autofills__RAND__();
			});

			if(!$j("#tag_id-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_tag_id__RAND__.value, t: 'Posts', f: 'tag_id' },
					success: function(resp) {
						$j('[name="tag_id"]').val(resp.results[0].id);
						$j('[id=tag_id-container-readonly__RAND__]').html('<span id="tag_id-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Tags_view_parent]').hide(); } else { $j('.btn[id=Tags_view_parent]').show(); }

						if(typeof(tag_id_update_autofills__RAND__) == 'function') tag_id_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_tag_id__RAND__.value, t: 'Posts', f: 'tag_id' },
				success: function(resp) {
					$j('[id=tag_id-container__RAND__], [id=tag_id-container-readonly__RAND__]').html('<span id="tag_id-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Tags_view_parent]').hide(); } else { $j('.btn[id=Tags_view_parent]').show(); }

					if(typeof(tag_id_update_autofills__RAND__) == 'function') tag_id_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/Posts_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/Posts_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Post details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Posts_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Posts_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Posts_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($separateDV ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#caregoria_id').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#caregoria_id_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#tag_id').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#tag_id_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#title').replaceWith('<div class=\"form-control-static\" id=\"title\">' + (jQuery('#title').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#data').parents('.input-group').replaceWith('<div class=\"form-control-static\" id=\"data\">' + (jQuery('#data').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#midia').replaceWith('<div class=\"form-control-static\" id=\"midia\">' + (jQuery('#midia').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$locale = isset($Translation['datetimepicker locale']) ? ", locale: '{$Translation['datetimepicker locale']}'" : '';
		$jsEditable .= "\tjQuery('#data').addClass('always_shown').parents('.input-group').datetimepicker({ toolbarPlacement: 'top', sideBySide: true, showClear: true, showTodayButton: true, showClose: true, icons: { close: 'glyphicon glyphicon-ok' }, format: AppGini.datetimeFormat('dt') {$locale} });";
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(caregoria_id)%%>', $combo_caregoria_id->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(caregoria_id)%%>', $combo_caregoria_id->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(caregoria_id)%%>', urlencode($combo_caregoria_id->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(tag_id)%%>', $combo_tag_id->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(tag_id)%%>', $combo_tag_id->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(tag_id)%%>', urlencode($combo_tag_id->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['caregoria_id' => ['Categoria', 'Caregoria id'], 'tag_id' => ['Tags', 'Tag id'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(caregoria_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(tag_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(title)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(conteudo)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(data)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(midia)%%>', ($noUploads ? '' : "<div>{$Translation['upload image']}</div>" . '<i class="glyphicon glyphicon-remove text-danger clear-upload hidden"></i> <input type="file" name="midia" id="midia" data-filetypes="jpg|jpeg|gif|png" data-maxsize="1048576" accept=".jpg,.jpeg,.gif,.png">'), $templateCode);
	if($AllowUpdate && $row['midia'] != '') {
		$templateCode = str_replace('<%%REMOVEFILE(midia)%%>', '<br><input type="checkbox" name="midia_remove" id="midia_remove" value="1"> <label for="midia_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	} else {
		$templateCode = str_replace('<%%REMOVEFILE(midia)%%>', '', $templateCode);
	}

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(caregoria_id)%%>', safe_html($urow['caregoria_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(caregoria_id)%%>', html_attr($row['caregoria_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(caregoria_id)%%>', urlencode($urow['caregoria_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(tag_id)%%>', safe_html($urow['tag_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(tag_id)%%>', html_attr($row['tag_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(tag_id)%%>', urlencode($urow['tag_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(title)%%>', safe_html($urow['title']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(title)%%>', html_attr($row['title']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(title)%%>', urlencode($urow['title']), $templateCode);
		if($AllowUpdate || $AllowInsert) {
			$templateCode = str_replace('<%%HTMLAREA(conteudo)%%>', '<textarea name="conteudo" id="conteudo" rows="5">' . safe_html(htmlspecialchars_decode($row['conteudo'])) . '</textarea>', $templateCode);
		} else {
			$templateCode = str_replace('<%%HTMLAREA(conteudo)%%>', '<div id="conteudo" class="form-control-static">' . $row['conteudo'] . '</div>', $templateCode);
		}
		$templateCode = str_replace('<%%VALUE(conteudo)%%>', nl2br($row['conteudo']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(conteudo)%%>', urlencode($urow['conteudo']), $templateCode);
		$templateCode = str_replace('<%%VALUE(data)%%>', app_datetime($row['data'], 'dt'), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(data)%%>', urlencode(app_datetime($urow['data'], 'dt')), $templateCode);
		$row['midia'] = ($row['midia'] != '' ? $row['midia'] : 'blank.gif');
		if( $dvprint) $templateCode = str_replace('<%%VALUE(midia)%%>', safe_html($urow['midia']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(midia)%%>', html_attr($row['midia']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(midia)%%>', urlencode($urow['midia']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(caregoria_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(caregoria_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(tag_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(tag_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(title)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(title)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%HTMLAREA(conteudo)%%>', '<textarea name="conteudo" id="conteudo" rows="5"></textarea>', $templateCode);
		$templateCode = str_replace('<%%VALUE(data)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(data)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(midia)%%>', 'blank.gif', $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Posts');
	if($selected_id) {
		$jdata = get_joined_record('Posts', $selected_id);
		if($jdata === false) $jdata = get_defaults('Posts');
		$rdata = $row;
	}
	$templateCode .= loadView('Posts-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: Posts_dv
	if(function_exists('Posts_dv')) {
		$args=[];
		Posts_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}