<?php
// This script and data application were generated by AppGini 22.11
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Posts.php');
	include_once(__DIR__ . '/Posts_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Posts');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Posts';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Posts`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Categoria1`.`Categoria`), CONCAT_WS('',   `Categoria1`.`Categoria`), '') /* Caregoria id */" => "caregoria_id",
		"IF(    CHAR_LENGTH(`Tags1`.`Tag`), CONCAT_WS('',   `Tags1`.`Tag`), '') /* Tag id */" => "tag_id",
		"`Posts`.`title`" => "title",
		"`Posts`.`conteudo`" => "conteudo",
		"if(`Posts`.`data`,date_format(`Posts`.`data`,'%m/%d/%Y %h:%i %p'),'')" => "data",
		"`Posts`.`midia`" => "midia",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Posts`.`id`',
		2 => '`Categoria1`.`Categoria`',
		3 => '`Tags1`.`Tag`',
		4 => 4,
		5 => 5,
		6 => '`Posts`.`data`',
		7 => 7,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Posts`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Categoria1`.`Categoria`), CONCAT_WS('',   `Categoria1`.`Categoria`), '') /* Caregoria id */" => "caregoria_id",
		"IF(    CHAR_LENGTH(`Tags1`.`Tag`), CONCAT_WS('',   `Tags1`.`Tag`), '') /* Tag id */" => "tag_id",
		"`Posts`.`title`" => "title",
		"`Posts`.`conteudo`" => "conteudo",
		"if(`Posts`.`data`,date_format(`Posts`.`data`,'%m/%d/%Y %h:%i %p'),'')" => "data",
		"`Posts`.`midia`" => "midia",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Posts`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`Categoria1`.`Categoria`), CONCAT_WS('',   `Categoria1`.`Categoria`), '') /* Caregoria id */" => "Caregoria id",
		"IF(    CHAR_LENGTH(`Tags1`.`Tag`), CONCAT_WS('',   `Tags1`.`Tag`), '') /* Tag id */" => "Tag id",
		"`Posts`.`title`" => "Title",
		"`Posts`.`conteudo`" => "Conteudo",
		"`Posts`.`data`" => "Data",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Posts`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Categoria1`.`Categoria`), CONCAT_WS('',   `Categoria1`.`Categoria`), '') /* Caregoria id */" => "caregoria_id",
		"IF(    CHAR_LENGTH(`Tags1`.`Tag`), CONCAT_WS('',   `Tags1`.`Tag`), '') /* Tag id */" => "tag_id",
		"`Posts`.`title`" => "title",
		"`Posts`.`conteudo`" => "conteudo",
		"if(`Posts`.`data`,date_format(`Posts`.`data`,'%m/%d/%Y %h:%i %p'),'')" => "data",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['caregoria_id' => 'Caregoria id', 'tag_id' => 'Tag id', ];

	$x->QueryFrom = "`Posts` LEFT JOIN `Categoria` as Categoria1 ON `Categoria1`.`id`=`Posts`.`caregoria_id` LEFT JOIN `Tags` as Tags1 ON `Tags1`.`id`=`Posts`.`tag_id` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 1;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Posts_view.php';
	$x->RedirectAfterInsert = 'Posts_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Posts';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`Posts`.`id`';
	$x->DefaultSortField = '`Posts`.`data`';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Caregoria id', 'Tag id', 'Title', 'Conteudo', 'Data', 'Midia', ];
	$x->ColFieldName = ['caregoria_id', 'tag_id', 'title', 'conteudo', 'data', 'midia', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Posts_templateTV.html';
	$x->SelectedTemplate = 'templates/Posts_templateTVS.html';
	$x->TemplateDV = 'templates/Posts_templateDV.html';
	$x->TemplateDVP = 'templates/Posts_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Posts_init
	$render = true;
	if(function_exists('Posts_init')) {
		$args = [];
		$render = Posts_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Posts_header
	$headerCode = '';
	if(function_exists('Posts_header')) {
		$args = [];
		$headerCode = Posts_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Posts_footer
	$footerCode = '';
	if(function_exists('Posts_footer')) {
		$args = [];
		$footerCode = Posts_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
